# Test case for BackendConfigPolicy with unknown cipher suites
# This should cause Envoy to NACK the configuration due to unrecognized cipher names
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - name: https
    port: 8443
    protocol: HTTPS
    hostname: www.example.com
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: gwtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: gwtest
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: BackendConfigPolicy
metadata:
  name: invalid-cipher-policy
  namespace: gwtest
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: example-svc
  tls:
    insecureSkipVerify: false
    parameters:
      minVersion: "1.2"
      maxVersion: "1.3"
      # Invalid cipher suites that Envoy doesn't recognize
      cipherSuites:
      - "BOGUS_CIPHER_SUITE_1"
      - "INVALID_AES_256_GCM_SHA384"
      - "FAKE_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      # Invalid ECDH curves
      ecdhCurves:
      - "invalid-curve-p256"
      - "bogus-secp384r1"
      - "fake-x25519"
