kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: gwtest
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      appProtocol: https
  selector:
    app: backend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: gwtest
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-service
          port: 443
---
# BackendConfigPolicy with non-existent TLS file paths - should cause validation error in strict mode
# Reproduces issue: https://github.com/kgateway-dev/kgateway/issues/12336
kind: BackendConfigPolicy
apiVersion: gateway.kgateway.dev/v1alpha1
metadata:
  name: invalid-tlsfiles-policy
  namespace: gwtest
spec:
  targetRefs:
    - name: backend-service
      group: ""
      kind: Service
  tls:
    files:
      # These file paths don't exist in the proxy filesystem
      tlsCertificate: "/nonexistent/path/to/cert.pem"
      tlsKey: "/invalid/path/to/key.pem"
      rootCA: "/missing/path/to/ca.pem"
    sni: "backend.example.com"
