kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: gwtest
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: gwtest
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-service
          port: 80
---
# BackendConfigPolicy with zero interval outlier detection - should cause validation error in strict mode
# Reproduces issue: https://github.com/kgateway-dev/kgateway/issues/12339
kind: BackendConfigPolicy
apiVersion: gateway.kgateway.dev/v1alpha1
metadata:
  name: invalid-outlier-detection-policy
  namespace: gwtest
spec:
  targetRefs:
    - name: backend-service
      group: ""
      kind: Service
  outlierDetection:
    consecutive5xx: 5
    interval: "0s" # Invalid: 0s interval should fail Envoy validation
    baseEjectionTime: "30s"
